#!/bin/bash

TEMPLATE_CONFIG=$1
SET_CONFIG=$2
SCENARIO_NAME=$3

AMI_ID="ami-2a7d75c0"

cp $TEMPLATE_CONFIG $SET_CONFIG

# echo $AUTH_DIR, $SSH_KEY, $VAULT_PSSWD
# echo $ENCRYPT_CRED, $WORK_DIR

sed -i "s#AUTH_DIR#${AUTH_DIR}#g" $SET_CONFIG
sed -i "s#SSH_KEY#${SSH_KEY}#g" $SET_CONFIG
sed -i "s#VAULT_PSSWD#${VAULT_PSSWD}#g" $SET_CONFIG
sed -i "s#CRED_FILE#${AWS_CREDS}#g" $SET_CONFIG
sed -i "s#ENCRYPT_CRED#${ENCRYPT_CRED}#g" $SET_CONFIG
sed -i "s#WORK_DIR#${WORK_DIR}#g" $SET_CONFIG
sed -i "s#CODE_DIR#${CODE_DIR}/yggdrasil#g" $SET_CONFIG
sed -i "s#SCENARIO_NAME#${SCENARIO_NAME}#g" $SET_CONFIG

sed -i "s#AMI_ID#${AMI_ID}#g" $SET_CONFIG